### ISSUE TITLE
pwalk_audit.c missing?

### ISSUE THREAD

**Issue by tenortim** [WhizBob/pwalk#1]
Compile fails with Makefile.onefs8 due to missing pwalk_audit.c file.

**Comment by WhizBob** [comment]
pwalk_audit.c was an incomplete code restructuring effort which aimed to eliminate the dependency on using Python coprocesses in the OneFS build to access WORM state metadata, and use the (Dell-private) pctl2() syscall instead  This file has been added to the repo, but I'm not sure if it was ever completed.   At the very least, if the USE_PCTL2 build variable is *not* set, it *should* still work the old way ... IIRC.
